// Search Translate Guard: generated opt-in site protection content script.

// Generated by node scripts/build.mjs. Do not edit directly.

// Source: src/core.js
(() => {
  "use strict";

  const runtimeSymbol = Symbol.for("search-translate-guard.runtime");
  if (globalThis[runtimeSymbol]) return;

  /**
   * @typedef {Object} GuardContext
   * @property {Document} document
   * @property {Location} location
   * @property {(element: Element) => void} protect
   * @property {(root: ParentNode | Element, selector: string) => Element[]} selectWithin
   */

  /**
   * @typedef {Object} ActivationRule
   * @property {string[]} events
   * @property {string} [selector]
   * @property {string} [key]
   * @property {boolean} [ignoreEditable]
   * @property {boolean} [unmodified]
   * @property {(event: Event, context: GuardContext) => boolean} [when]
   */

  /**
   * @typedef {Object} GuardAdapter
   * @property {string} id
   * @property {(url: URL) => boolean} matches
   * @property {{ select(root: ParentNode | Element, context: GuardContext): Iterable<Element> }} protection
   * @property {{ type: string, root(event: Event): ParentNode | Element | null | undefined }[]} [beforeAttachEvents]
   * @property {string[]} [rescanEvents]
   * @property {{
   *   activationRules: ActivationRule[],
   *   delayMs: number,
   *   isHealthy(context: GuardContext): boolean,
   *   recover(context: GuardContext): void
   * }} [recovery]
   */

  /** @type {GuardAdapter[]} */
  const adapters = [];
  /** @type {GuardAdapter[]} */
  const activeAdapters = [];
  const contexts = new Map();
  const timers = new Map();
  let started = false;

  function protect(element) {
    if (!(element instanceof Element)) return;
    element.setAttribute("translate", "no");
    element.classList.add("notranslate");
  }

  function selectWithin(root, selector) {
    const matches = [];
    if (root instanceof Element && root.matches(selector)) matches.push(root);
    root?.querySelectorAll?.(selector).forEach((element) => matches.push(element));
    return matches;
  }

  function isEditable(target) {
    const element = target instanceof Element ? target : target?.parentElement;
    return Boolean(element?.closest(
      'input, textarea, select, [contenteditable="true"], [role="textbox"]'
    ));
  }

  function registerAdapter(adapter) {
    if (!adapter || typeof adapter.id !== "string" || !adapter.id) {
      throw new TypeError("Guard adapter id must be a non-empty string");
    }
    if (adapters.some((candidate) => candidate.id === adapter.id)) {
      throw new Error(`Guard adapter already registered: ${adapter.id}`);
    }
    if (typeof adapter.matches !== "function" || typeof adapter.protection?.select !== "function") {
      throw new TypeError(`Guard adapter ${adapter.id} is missing matches() or protection.select()`);
    }
    adapters.push(adapter);
    if (started) activateAdapter(adapter);
  }

  function ruleMatches(rule, event, context) {
    if (!rule.events.includes(event.type)) return false;
    if (rule.key !== undefined && !(event instanceof KeyboardEvent && event.key === rule.key)) {
      return false;
    }
    if (
      rule.unmodified &&
      event instanceof KeyboardEvent &&
      (event.ctrlKey || event.altKey || event.metaKey)
    ) {
      return false;
    }
    if (rule.ignoreEditable && isEditable(event.target)) return false;

    if (rule.selector) {
      const target = event.target instanceof Element ? event.target : event.target?.parentElement;
      if (!target?.closest(rule.selector)) return false;
    }

    return rule.when ? Boolean(rule.when(event, context)) : true;
  }

  function contextFor(adapter) {
    if (!contexts.has(adapter)) contexts.set(adapter, {
      document,
      location,
      protect,
      selectWithin
    });
    return contexts.get(adapter);
  }

  function scan(adapter, root) {
    if (
      !(root instanceof Element) &&
      !(root instanceof Document) &&
      !(root instanceof DocumentFragment)
    ) {
      return;
    }

    const context = contextFor(adapter);
    for (const element of adapter.protection.select(root, context) ?? []) protect(element);
  }

  function scanAll(root) {
    for (const adapter of activeAdapters) scan(adapter, root);
  }

  function activateAdapter(adapter) {
    if (activeAdapters.includes(adapter) || !adapter.matches(new URL(location.href))) return;
    activeAdapters.push(adapter);
    const context = contextFor(adapter);
    scan(adapter, document);

    for (const hook of adapter.beforeAttachEvents ?? []) {
      document.addEventListener(hook.type, (event) => {
        scan(adapter, hook.root(event));
      }, true);
    }

    for (const eventType of adapter.rescanEvents ?? []) {
      document.addEventListener(eventType, () => scan(adapter, document), true);
    }

    if (!adapter.recovery) return;

    const scheduleRecoveryCheck = () => {
      clearTimeout(timers.get(adapter));
      timers.set(adapter, setTimeout(() => {
        if (!adapter.recovery.isHealthy(context)) adapter.recovery.recover(context);
      }, adapter.recovery.delayMs));
    };

    const eventTypes = new Set(
      adapter.recovery.activationRules.flatMap((rule) => rule.events)
    );
    for (const eventType of eventTypes) {
      document.addEventListener(eventType, (event) => {
        if (adapter.recovery.activationRules.some((rule) => ruleMatches(rule, event, context))) {
          scheduleRecoveryCheck();
        }
      }, true);
    }
  }

  function start() {
    if (started) return;
    started = true;

    new MutationObserver((records) => {
      for (const record of records) {
        for (const node of record.addedNodes) scanAll(node);
      }
    }).observe(document, { childList: true, subtree: true });

    for (const adapter of adapters) activateAdapter(adapter);
  }

  Object.defineProperty(globalThis, runtimeSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: Object.freeze({ protect, registerAdapter, selectWithin, start })
  });
})();

// Source: src/adapters/site-rules.js
(() => {
  "use strict";

  const runtime = globalThis[Symbol.for("search-translate-guard.runtime")];
  if (!runtime) throw new Error("Search Translate Guard core must load before adapters");

  const storageKey = "siteGuardConfig";
  const origin = location.origin;
  const stateSymbol = Symbol.for(`search-translate-guard.site-rules:${origin}`);
  const existingState = globalThis[stateSymbol];
  if (existingState) {
    void existingState.reload();
    return;
  }

  let previousState = new WeakMap();
  let selectors = [];

  function validSelectors(rules) {
    const accepted = [];
    for (const rule of Array.isArray(rules) ? rules : []) {
      const selector = typeof rule?.selector === "string" ? rule.selector.trim() : "";
      if (!selector || selector.length > 512) continue;
      try {
        document.querySelector(selector);
        accepted.push(selector);
      } catch {
        // Ignore stale or invalid local rules without breaking the page.
      }
    }
    return [...new Set(accepted)];
  }

  function remember(element) {
    if (!previousState.has(element)) {
      previousState.set(element, {
        translate: element.getAttribute("translate"),
        hadNoTranslateClass: element.classList.contains("notranslate"),
        marker: element.getAttribute("data-search-translate-guard-rule")
      });
    }
    element.setAttribute("data-search-translate-guard-rule", "true");
    return element;
  }

  function restoreProtectedElements() {
    document.querySelectorAll('[data-search-translate-guard-rule="true"]').forEach((element) => {
      const previous = previousState.get(element);
      if (!previous) return;

      if (element.getAttribute("translate") === "no") {
        if (previous.translate === null) element.removeAttribute("translate");
        else element.setAttribute("translate", previous.translate);
      }
      if (!previous.hadNoTranslateClass) element.classList.remove("notranslate");
      if (previous.marker === null) element.removeAttribute("data-search-translate-guard-rule");
      else element.setAttribute("data-search-translate-guard-rule", previous.marker);
    });
    previousState = new WeakMap();
  }

  function selectTargets(root) {
    const targets = [];
    for (const selector of selectors) {
      for (const element of runtime.selectWithin(root, selector)) targets.push(remember(element));
    }
    return [...new Set(targets)];
  }

  function updateRules(rules) {
    restoreProtectedElements();
    selectors = validSelectors(rules);
    for (const element of selectTargets(document)) runtime.protect(element);
  }

  async function reload() {
    const stored = await chrome.storage.local.get(storageKey);
    const site = stored[storageKey]?.sites?.[origin];
    updateRules(site?.enabled ? site.rules : []);
  }

  const state = Object.freeze({ reload, updateRules });
  Object.defineProperty(globalThis, stateSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: state
  });

  runtime.registerAdapter({
    id: `site-rules:${origin}`,
    matches: (url) => url.origin === origin,
    protection: { select: selectTargets }
  });
  runtime.start();

  chrome.runtime.onMessage.addListener((message) => {
    if (message?.type === "site-guard:rules-updated" && message.origin === origin) {
      updateRules(message.rules);
    }
  });

  void reload();
})();
