// Search Translate Guard: generated opt-in site protection content script.

// Generated by node scripts/build.mjs. Do not edit directly.

// Source: src/core.js
(() => {
  "use strict";

  const runtimeSymbol = Symbol.for("search-translate-guard.runtime");
  if (globalThis[runtimeSymbol]) return;

  /**
   * @typedef {Object} GuardContext
   * @property {Document} document
   * @property {Location} location
   * @property {(element: Element) => void} protect
   * @property {(root: ParentNode | Element, selector: string) => Element[]} selectWithin
   */

  /**
   * @typedef {Object} ActivationRule
   * @property {string[]} events
   * @property {string} [selector]
   * @property {string} [key]
   * @property {boolean} [ignoreEditable]
   * @property {boolean} [unmodified]
   * @property {(event: Event, context: GuardContext) => boolean} [when]
   */

  /**
   * @typedef {Object} GuardAdapter
   * @property {string} id
   * @property {(url: URL) => boolean} matches
   * @property {{ select(root: ParentNode | Element, context: GuardContext): Iterable<Element> }} protection
   * @property {{ type: string, root(event: Event): ParentNode | Element | null | undefined }[]} [beforeAttachEvents]
   * @property {string[]} [rescanEvents]
   * @property {{
   *   activationRules: ActivationRule[],
   *   delayMs: number,
   *   isHealthy(context: GuardContext): boolean,
   *   recover(context: GuardContext): void
   * }} [recovery]
   */

  /** @type {GuardAdapter[]} */
  const adapters = [];
  /** @type {GuardAdapter[]} */
  const activeAdapters = [];
  const contexts = new Map();
  const timers = new Map();
  let started = false;

  function protect(element) {
    if (!(element instanceof Element)) return;
    element.setAttribute("translate", "no");
    element.classList.add("notranslate");
  }

  function selectWithin(root, selector) {
    const matches = [];
    if (root instanceof Element && root.matches(selector)) matches.push(root);
    root?.querySelectorAll?.(selector).forEach((element) => matches.push(element));
    return matches;
  }

  function isEditable(target) {
    const element = target instanceof Element ? target : target?.parentElement;
    return Boolean(element?.closest(
      'input, textarea, select, [contenteditable="true"], [role="textbox"]'
    ));
  }

  function registerAdapter(adapter) {
    if (!adapter || typeof adapter.id !== "string" || !adapter.id) {
      throw new TypeError("Guard adapter id must be a non-empty string");
    }
    if (adapters.some((candidate) => candidate.id === adapter.id)) {
      throw new Error(`Guard adapter already registered: ${adapter.id}`);
    }
    if (typeof adapter.matches !== "function" || typeof adapter.protection?.select !== "function") {
      throw new TypeError(`Guard adapter ${adapter.id} is missing matches() or protection.select()`);
    }
    adapters.push(adapter);
    if (started) activateAdapter(adapter);
  }

  function ruleMatches(rule, event, context) {
    if (!rule.events.includes(event.type)) return false;
    if (rule.key !== undefined && !(event instanceof KeyboardEvent && event.key === rule.key)) {
      return false;
    }
    if (
      rule.unmodified &&
      event instanceof KeyboardEvent &&
      (event.ctrlKey || event.altKey || event.metaKey)
    ) {
      return false;
    }
    if (rule.ignoreEditable && isEditable(event.target)) return false;

    if (rule.selector) {
      const target = event.target instanceof Element ? event.target : event.target?.parentElement;
      if (!target?.closest(rule.selector)) return false;
    }

    return rule.when ? Boolean(rule.when(event, context)) : true;
  }

  function contextFor(adapter) {
    if (!contexts.has(adapter)) contexts.set(adapter, {
      document,
      location,
      protect,
      selectWithin
    });
    return contexts.get(adapter);
  }

  function scan(adapter, root) {
    if (
      !(root instanceof Element) &&
      !(root instanceof Document) &&
      !(root instanceof DocumentFragment)
    ) {
      return;
    }

    const context = contextFor(adapter);
    for (const element of adapter.protection.select(root, context) ?? []) protect(element);
  }

  function scanAll(root) {
    for (const adapter of activeAdapters) scan(adapter, root);
  }

  function activateAdapter(adapter) {
    if (activeAdapters.includes(adapter) || !adapter.matches(new URL(location.href))) return;
    activeAdapters.push(adapter);
    const context = contextFor(adapter);
    scan(adapter, document);

    for (const hook of adapter.beforeAttachEvents ?? []) {
      document.addEventListener(hook.type, (event) => {
        scan(adapter, hook.root(event));
      }, true);
    }

    for (const eventType of adapter.rescanEvents ?? []) {
      document.addEventListener(eventType, () => scan(adapter, document), true);
    }

    if (!adapter.recovery) return;

    const scheduleRecoveryCheck = () => {
      clearTimeout(timers.get(adapter));
      timers.set(adapter, setTimeout(() => {
        if (!adapter.recovery.isHealthy(context)) adapter.recovery.recover(context);
      }, adapter.recovery.delayMs));
    };

    const eventTypes = new Set(
      adapter.recovery.activationRules.flatMap((rule) => rule.events)
    );
    for (const eventType of eventTypes) {
      document.addEventListener(eventType, (event) => {
        if (adapter.recovery.activationRules.some((rule) => ruleMatches(rule, event, context))) {
          scheduleRecoveryCheck();
        }
      }, true);
    }
  }

  function start() {
    if (started) return;
    started = true;

    new MutationObserver((records) => {
      for (const record of records) {
        for (const node of record.addedNodes) scanAll(node);
      }
    }).observe(document, { childList: true, subtree: true });

    for (const adapter of adapters) activateAdapter(adapter);
  }

  Object.defineProperty(globalThis, runtimeSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: Object.freeze({ protect, registerAdapter, selectWithin, start })
  });
})();

// Source: src/risk-detector.js
(() => {
  "use strict";

  const detectorSymbol = Symbol.for("search-translate-guard.risk-detector");
  if (globalThis[detectorSymbol]) return;

  const compositeRoles = new Set([
    "combobox", "listbox", "menu", "tree", "grid", "tablist"
  ]);
  const frameworkPrefixes = [
    "data-radix-", "data-headlessui-", "data-reach-", "data-floating-ui-"
  ];
  const ignoredTags = new Set([
    "html", "head", "body", "script", "style", "link", "meta", "svg", "path"
  ]);

  function addSignal(result, name, weight) {
    if (result.reasons.includes(name)) return;
    result.reasons.push(name);
    result.score += weight;
  }

  function isVisible(element) {
    const rect = element.getBoundingClientRect();
    if (rect.width < 8 || rect.height < 8) return false;
    const style = getComputedStyle(element);
    return style.display !== "none" && style.visibility !== "hidden";
  }

  /**
   * Find a bounded interactive component boundary without reading text.
   * @param {Element} target
   * @returns {Element | null}
   */
  function boundaryFor(target) {
    if (!(target instanceof Element)) return null;
    if ([document.body, document.documentElement].includes(target)) return null;
    const semantic = target.closest([
      "input", "textarea", "select", "button", "[contenteditable=true]",
      "[role=combobox]", "[role=listbox]", "[role=dialog]", "[role=menu]",
      "[role=tree]", "[role=grid]", "[role=tablist]", "[role=textbox]"
    ].join(",")) || target;

    let candidate = semantic;
    let ancestor = semantic.parentElement;
    for (let depth = 0; ancestor && depth < 3; depth += 1, ancestor = ancestor.parentElement) {
      if (
        ancestor.localName.includes("-") ||
        ancestor.matches("[role=combobox], [role=listbox], [role=dialog], [role=menu], [role=tree], [role=grid], [role=tablist]")
      ) {
        candidate = ancestor;
        break;
      }
    }
    return [document.body, document.documentElement].includes(candidate) ? null : candidate;
  }

  /**
   * Score structural interaction signals only. Visible text, field values, and
   * application data are deliberately excluded.
   * @param {Element} element
   * @returns {{ score: number, reasons: string[] }}
   */
  function score(element) {
    const result = { score: 0, reasons: [] };
    if (!(element instanceof Element) || ignoredTags.has(element.localName)) return result;

    const tag = element.localName;
    const role = element.getAttribute("role")?.toLowerCase() || "";
    if (tag.includes("-")) {
      addSignal(result, "custom-element", 2);
      if (element.querySelector([
        "input", "textarea", "select", "button", "[contenteditable]",
        "[role=combobox]", "[role=listbox]", "[role=dialog]", "[role=menu]"
      ].join(","))) {
        addSignal(result, "interactive-descendant", 2);
      }
    }
    if (tag === "dialog" || role === "dialog" || role === "alertdialog") {
      addSignal(result, "dialog", 5);
    }
    if (compositeRoles.has(role)) addSignal(result, "composite-role", 5);
    if (tag === "select") addSignal(result, "select-control", 4);
    if (
      tag === "textarea" ||
      role === "textbox" ||
      (tag === "input" && !["hidden", "checkbox", "radio", "submit", "button"].includes(
        element.getAttribute("type")?.toLowerCase() || "text"
      ))
    ) {
      addSignal(result, "editable-control", 2);
    }
    if (element.matches('[contenteditable="true"], [contenteditable="plaintext-only"]')) {
      addSignal(result, "editable-control", 2);
    }
    if (element.hasAttribute("aria-controls")) addSignal(result, "aria-controls", 2);
    if (element.hasAttribute("aria-expanded")) addSignal(result, "aria-expanded", 2);
    if (element.hasAttribute("aria-haspopup")) addSignal(result, "aria-popup", 2);
    if (element.hasAttribute("popover")) addSignal(result, "popover", 3);
    if (element.hasAttribute("data-state")) addSignal(result, "framework-state", 2);

    for (const attribute of element.attributes) {
      if (frameworkPrefixes.some((prefix) => attribute.name.startsWith(prefix))) {
        addSignal(result, "framework-state", 2);
        break;
      }
    }

    return result;
  }

  /**
   * @param {Document | Element} [root]
   * @param {{ maxElements?: number, maxSuggestions?: number, minimumScore?: number }} [options]
   * @returns {{ element: Element, score: number, reasons: string[] }[]}
   */
  function detect(root = document, options = {}) {
    const maxElements = Math.max(1, Math.min(Number(options.maxElements) || 3000, 5000));
    const maxSuggestions = Math.max(1, Math.min(Number(options.maxSuggestions) || 24, 50));
    const minimumScore = Math.max(1, Math.min(Number(options.minimumScore) || 4, 20));
    const ownerDocument = root instanceof Document ? root : root.ownerDocument || document;
    const walker = ownerDocument.createTreeWalker(root, NodeFilter.SHOW_ELEMENT);
    const suggestions = [];
    let visited = 0;

    while (walker.nextNode() && visited < maxElements) {
      visited += 1;
      const element = walker.currentNode;
      if (!(element instanceof Element) || !isVisible(element)) continue;
      const result = score(element);
      if (result.score < minimumScore) continue;
      suggestions.push({ element, score: result.score, reasons: result.reasons });
    }

    return suggestions
      .sort((left, right) => right.score - left.score)
      .slice(0, maxSuggestions);
  }

  Object.defineProperty(globalThis, detectorSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: Object.freeze({ boundaryFor, detect, isVisible, score })
  });
})();

// Source: src/mutation-risk-observer.js
(() => {
  "use strict";

  const observerSymbol = Symbol.for("search-translate-guard.mutation-risk-observer");
  if (globalThis[observerSymbol]) return;

  const detector = globalThis[Symbol.for("search-translate-guard.risk-detector")];
  if (!detector?.boundaryFor || !detector?.isVisible || !detector?.score) {
    throw new Error("Risk detector must load before mutation risk observation");
  }

  const maxCandidates = 24;
  const candidateTtlMs = 15 * 60 * 1_000;
  const observations = new Map();
  let enabled = false;

  function containsTextNode(node) {
    if (node.nodeType === Node.TEXT_NODE) return true;
    if (!(node instanceof Element)) return false;
    const walker = document.createTreeWalker(
      node,
      NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT
    );
    for (let visited = 0; visited < 200 && walker.nextNode(); visited += 1) {
      if (walker.currentNode.nodeType === Node.TEXT_NODE) return true;
    }
    return false;
  }

  function someNode(nodes, predicate) {
    const limit = Math.min(nodes.length, 100);
    for (let index = 0; index < limit; index += 1) {
      if (predicate(nodes[index])) return true;
    }
    return false;
  }

  function rewriteEvidence(record) {
    return {
      removedText: someNode(
        record.removedNodes,
        (node) => node.nodeType === Node.TEXT_NODE
      ),
      addedWrapper: someNode(record.addedNodes, (node) => (
        node instanceof Element && containsTextNode(node)
      ))
    };
  }

  function isInteractiveBoundary(element) {
    return element.localName.includes("-") || element.matches([
      "button", "input", "textarea", "select", "dialog", "[contenteditable]",
      "[role=combobox]", "[role=listbox]", "[role=dialog]", "[role=menu]",
      "[role=tree]", "[role=grid]", "[role=tablist]", "[role=textbox]", "[popover]"
    ].join(","));
  }

  function prune(now = Date.now()) {
    for (const [element, observation] of observations) {
      if (!element.isConnected || now - observation.observedAt > candidateTtlMs) {
        observations.delete(element);
      }
    }
  }

  function remember(element) {
    if (
      !(element instanceof Element) ||
      !isInteractiveBoundary(element) ||
      !detector.isVisible(element)
    ) return;
    if (element.closest('[translate="no"], .notranslate')) return;

    const structural = detector.score(element);
    const previous = observations.get(element);
    const observation = {
      element,
      score: Math.min(20, Math.max(8, structural.score + 6) + Math.min(previous?.occurrences || 0, 3)),
      reasons: [...new Set(["observed-text-rewrite", ...structural.reasons])],
      observedAt: Date.now(),
      occurrences: Math.min((previous?.occurrences || 0) + 1, 4)
    };
    observations.set(element, observation);
    prune(observation.observedAt);

    if (observations.size > maxCandidates) {
      const oldest = [...observations.values()]
        .sort((left, right) => left.observedAt - right.observedAt)[0];
      if (oldest) observations.delete(oldest.element);
    }
  }

  function process(records) {
    if (document.visibilityState === "hidden") return;
    const byTarget = new Map();
    for (const record of records.slice(0, 200)) {
      if (record.type !== "childList") continue;
      const evidence = rewriteEvidence(record);
      if (!evidence.removedText && !evidence.addedWrapper) continue;
      const previous = byTarget.get(record.target) || {
        removedText: false,
        addedWrapper: false
      };
      previous.removedText ||= evidence.removedText;
      previous.addedWrapper ||= evidence.addedWrapper;
      byTarget.set(record.target, previous);
    }
    for (const [mutationTarget, evidence] of byTarget) {
      if (!evidence.removedText || !evidence.addedWrapper) continue;
      const target = mutationTarget instanceof Element
        ? mutationTarget
        : mutationTarget.parentElement;
      const boundary = detector.boundaryFor(target);
      if (boundary) remember(boundary);
    }
  }

  function candidates() {
    if (!enabled) return [];
    prune();
    return [...observations.values()]
      .sort((left, right) => right.score - left.score || right.observedAt - left.observedAt)
      .map(({ element, score, reasons, observedAt, occurrences }) => ({
        element,
        score,
        reasons: [...reasons],
        observedAt,
        occurrences
      }));
  }

  const observer = new MutationObserver(process);

  function setEnabled(value) {
    const next = Boolean(value);
    if (enabled === next) return;
    enabled = next;
    if (enabled) {
      observer.observe(document, { childList: true, subtree: true });
    } else {
      observer.disconnect();
      observations.clear();
    }
  }

  setEnabled(true);

  Object.defineProperty(globalThis, observerSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: Object.freeze({
      candidates,
      count: () => candidates().length,
      setEnabled
    })
  });
})();

// Source: src/selector-tools.js
(() => {
  "use strict";

  const toolsSymbol = Symbol.for("search-translate-guard.selector-tools");
  if (globalThis[toolsSymbol]) return;

  const fingerprintKeys = ["tag", "role", "type", "name", "landmark"];

  function escapeIdentifier(value) {
    return globalThis.CSS?.escape
      ? CSS.escape(value)
      : value.replace(/[^a-zA-Z0-9_-]/g, (character) => `\\${character}`);
  }

  function escapeAttribute(value) {
    return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  }

  function isUnique(candidate) {
    try {
      return document.querySelectorAll(candidate).length === 1;
    } catch {
      return false;
    }
  }

  function stableSegment(element) {
    const tag = element.localName;
    if (element.id) {
      const candidate = `#${escapeIdentifier(element.id)}`;
      if (isUnique(candidate)) return { value: candidate, unique: true };
    }

    for (const name of ["data-testid", "data-test", "data-target", "data-component"]) {
      const value = element.getAttribute(name);
      if (!value || value.length > 120) continue;
      const candidate = `${tag}[${name}="${escapeAttribute(value)}"]`;
      if (isUnique(candidate)) return { value: candidate, unique: true };
    }

    let value = tag;
    for (const name of ["role", "name", "type"]) {
      const attribute = element.getAttribute(name);
      if (attribute && attribute.length <= 80) {
        value += `[${name}="${escapeAttribute(attribute)}"]`;
      }
    }

    const stableClasses = [...element.classList]
      .filter((name) => /^[a-zA-Z][\w-]{0,40}$/.test(name))
      .filter((name) => !/^(active|current|focus|hover|open|selected|disabled)$/i.test(name))
      .slice(0, 2);
    if (stableClasses.length) {
      value += stableClasses.map((name) => `.${escapeIdentifier(name)}`).join("");
    }

    const siblings = element.parentElement
      ? [...element.parentElement.children].filter((candidate) => candidate.localName === tag)
      : [];
    if (siblings.length > 1) value += `:nth-of-type(${siblings.indexOf(element) + 1})`;
    return { value, unique: isUnique(value) };
  }

  function selectorFor(element) {
    if (!(element instanceof Element)) return "";
    const parts = [];
    let current = element;
    for (let depth = 0; current && current !== document.documentElement && depth < 6; depth += 1) {
      const segment = stableSegment(current);
      parts.unshift(segment.value);
      const candidate = parts.join(" > ");
      if (segment.unique || isUnique(candidate)) return candidate;
      current = current.parentElement;
    }
    return parts.join(" > ");
  }

  function landmarkFor(element) {
    const landmark = element.closest(
      "header, nav, main, form, [role=dialog], [role=main], [role=navigation]"
    );
    return landmark ? landmark.localName : "";
  }

  function fingerprintFor(element) {
    return {
      tag: element.localName,
      role: element.getAttribute("role") || "",
      type: element.getAttribute("type") || "",
      name: element.getAttribute("name") || "",
      landmark: landmarkFor(element)
    };
  }

  function normalizedFingerprint(value) {
    const fingerprint = {};
    if (!value || typeof value !== "object") return fingerprint;
    for (const key of fingerprintKeys) {
      const candidate = value[key];
      if (typeof candidate === "string" && candidate.length <= 120) {
        fingerprint[key] = candidate;
      }
    }
    return fingerprint;
  }

  function isRebindableFingerprint(value) {
    const fingerprint = normalizedFingerprint(value);
    if (!/^[a-z][a-z0-9-]*$/.test(fingerprint.tag || "")) return false;
    let strength = fingerprint.tag.includes("-") ? 2 : 0;
    if (fingerprint.role) strength += 3;
    if (fingerprint.type) strength += 1;
    if (fingerprint.name) strength += 2;
    if (fingerprint.landmark) strength += 1;
    return strength >= 3;
  }

  function matchesFingerprint(element, value) {
    if (!(element instanceof Element)) return false;
    const fingerprint = normalizedFingerprint(value);
    if (fingerprint.tag && element.localName !== fingerprint.tag) return false;
    if (fingerprint.role && element.getAttribute("role") !== fingerprint.role) return false;
    if (fingerprint.type && element.getAttribute("type") !== fingerprint.type) return false;
    if (fingerprint.name && element.getAttribute("name") !== fingerprint.name) return false;
    if (fingerprint.landmark && landmarkFor(element) !== fingerprint.landmark) return false;
    return Boolean(Object.values(fingerprint).some(Boolean));
  }

  function candidateSelector(value) {
    const fingerprint = normalizedFingerprint(value);
    if (!/^[a-z][a-z0-9-]*$/.test(fingerprint.tag || "")) return "";
    let selector = fingerprint.tag;
    for (const name of ["role", "type", "name"]) {
      const attribute = fingerprint[name];
      if (attribute) selector += `[${name}="${escapeAttribute(attribute)}"]`;
    }
    return selector;
  }

  function fingerprintMatches(root, fingerprint, limit = Number.POSITIVE_INFINITY) {
    if (!isRebindableFingerprint(fingerprint)) return [];
    const selector = candidateSelector(fingerprint);
    if (!selector || !root?.querySelectorAll) return [];
    const matches = [];
    for (const element of root.querySelectorAll(selector)) {
      if (!matchesFingerprint(element, fingerprint)) continue;
      matches.push(element);
      if (matches.length >= limit) break;
    }
    return matches;
  }

  function uniqueFingerprintMatch(root, fingerprint) {
    const matches = fingerprintMatches(root, fingerprint, 2);
    return matches.length === 1 ? matches[0] : null;
  }

  Object.defineProperty(globalThis, toolsSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: Object.freeze({
      fingerprintFor,
      fingerprintMatches,
      isRebindableFingerprint,
      matchesFingerprint,
      normalizedFingerprint,
      selectorFor,
      uniqueFingerprintMatch
    })
  });
})();

// Source: src/adapters/site-rules.js
(() => {
  "use strict";

  const runtime = globalThis[Symbol.for("search-translate-guard.runtime")];
  const selectorTools = globalThis[Symbol.for("search-translate-guard.selector-tools")];
  const mutationRisks = globalThis[Symbol.for("search-translate-guard.mutation-risk-observer")];
  if (!runtime || !selectorTools) {
    throw new Error("Search Translate Guard core and selector tools must load before site rules");
  }

  const storageKey = "siteGuardConfig";
  const origin = location.origin;
  const stateSymbol = Symbol.for(`search-translate-guard.site-rules:${origin}`);
  const existingState = globalThis[stateSymbol];
  if (existingState) {
    void existingState.reload();
    return;
  }

  let previousState = new WeakMap();
  let rules = [];
  let reconcileTimer = null;
  let waitsForDomReady = false;
  const rebindCandidates = new Map();
  const rebindNotifications = new Map();
  const rebindRetryCounts = new Map();
  const rebindStabilityMs = 250;
  const maxRebindRetries = 3;

  function normalizedRules(value) {
    const accepted = [];
    const ids = new Set();
    for (const rawRule of Array.isArray(value) ? value : []) {
      const selector = typeof rawRule?.selector === "string" ? rawRule.selector.trim() : "";
      if (!selector || selector.length > 512) continue;
      const id = typeof rawRule.id === "string" && rawRule.id
        ? rawRule.id
        : `legacy:${selector}`;
      if (ids.has(id)) continue;
      ids.add(id);
      accepted.push({
        id,
        selector,
        fingerprint: selectorTools.normalizedFingerprint(rawRule.fingerprint)
      });
    }
    return accepted;
  }

  function remember(element) {
    if (!previousState.has(element)) {
      previousState.set(element, {
        translate: element.getAttribute("translate"),
        hadNoTranslateClass: element.classList.contains("notranslate"),
        marker: element.getAttribute("data-search-translate-guard-rule")
      });
    }
    element.setAttribute("data-search-translate-guard-rule", "true");
    return element;
  }

  function restoreProtectedElements() {
    document.querySelectorAll('[data-search-translate-guard-rule="true"]').forEach((element) => {
      const previous = previousState.get(element);
      if (!previous) return;

      if (element.getAttribute("translate") === "no") {
        if (previous.translate === null) element.removeAttribute("translate");
        else element.setAttribute("translate", previous.translate);
      }
      if (!previous.hadNoTranslateClass) element.classList.remove("notranslate");
      if (previous.marker === null) element.removeAttribute("data-search-translate-guard-rule");
      else element.setAttribute("data-search-translate-guard-rule", previous.marker);
    });
    previousState = new WeakMap();
  }

  function queryRule(rule) {
    try {
      return [...document.querySelectorAll(rule.selector)];
    } catch {
      return [];
    }
  }

  function isSelectorValid(rule) {
    try {
      document.querySelector(rule.selector);
      return true;
    } catch {
      return false;
    }
  }

  function matchingRuleElements(rule) {
    const elements = queryRule(rule);
    if (!selectorTools.isRebindableFingerprint(rule.fingerprint)) return elements;
    return elements.filter((element) => selectorTools.matchesFingerprint(element, rule.fingerprint));
  }

  function stableSelectorForRebind(rule, element) {
    if ((rebindRetryCounts.get(rule.id) || 0) > maxRebindRetries) return "";
    const selector = selectorTools.selectorFor(element);
    if (!selector || selector.length > 512 || selector === rule.selector) return "";
    const now = Date.now();
    const pending = rebindCandidates.get(rule.id);
    if (!pending || pending.selector !== selector || pending.element !== element) {
      rebindCandidates.set(rule.id, { element, selector, firstSeenAt: now });
      scheduleReconcile(rebindStabilityMs);
      return "";
    }
    const elapsed = now - pending.firstSeenAt;
    if (elapsed < rebindStabilityMs) {
      scheduleReconcile(rebindStabilityMs - elapsed);
      return "";
    }
    rebindCandidates.delete(rule.id);
    return selector;
  }

  function sendRebind(rule, element, selector) {
    if (!selector || rebindNotifications.get(rule.id) === selector) return;
    rebindNotifications.set(rule.id, selector);

    try {
      chrome.runtime.sendMessage({
        type: "site-guard:rebind-rule",
        origin,
        rule: {
          id: rule.id,
          selector,
          fingerprint: selectorTools.fingerprintFor(element)
        }
      }, (response) => {
        if (chrome.runtime.lastError || !response?.ok) {
          handleRebindFailure(rule.id);
          return;
        }
        rule.selector = selector;
        rule.fingerprint = selectorTools.normalizedFingerprint(
          response.result?.fingerprint || rule.fingerprint
        );
        rebindNotifications.delete(rule.id);
        rebindRetryCounts.delete(rule.id);
      });
    } catch {
      // Extension shutdown or a disconnected service worker must not affect the page.
      handleRebindFailure(rule.id);
    }
  }

  function handleRebindFailure(ruleId) {
    rebindNotifications.delete(ruleId);
    const failures = (rebindRetryCounts.get(ruleId) || 0) + 1;
    rebindRetryCounts.set(ruleId, failures);
    if (failures <= maxRebindRetries) {
      scheduleReconcile(1_000 * (2 ** (failures - 1)));
    }
  }

  function ruleHealth(rule) {
    if (!isSelectorValid(rule)) return "invalid";
    const selected = queryRule(rule);
    if (!selectorTools.isRebindableFingerprint(rule.fingerprint)) {
      return selected.length ? "healthy" : "weak";
    }

    const directMatches = selected.filter((element) => (
      selectorTools.matchesFingerprint(element, rule.fingerprint)
    ));
    if (directMatches.length === 1 && selected.length === 1) return "healthy";
    if (directMatches.length > 1) return "ambiguous";

    const candidates = selectorTools.fingerprintMatches(document, rule.fingerprint, 2);
    if (candidates.length > 1) return "ambiguous";
    if (candidates.length === 1) return "recovering";
    return "missing";
  }

  function healthSnapshot() {
    const observedRiskCount = Number(mutationRisks?.count?.()) || 0;
    return {
      origin,
      observedRiskCount: Math.max(0, Math.min(observedRiskCount, 24)),
      rules: rules.map((rule) => ({ id: rule.id, state: ruleHealth(rule) }))
    };
  }

  function reconcileRules() {
    reconcileTimer = null;
    if (document.readyState === "loading") {
      scheduleReconcile();
      return;
    }

    for (const rule of rules) {
      if (!selectorTools.isRebindableFingerprint(rule.fingerprint)) continue;
      const directMatches = matchingRuleElements(rule);
      if (directMatches.length === 1) {
        const element = directMatches[0];
        runtime.protect(remember(element));
        if (queryRule(rule).length !== 1) {
          const selector = stableSelectorForRebind(rule, element);
          if (selector) sendRebind(rule, element, selector);
        }
        continue;
      }
      if (directMatches.length > 1) {
        rebindCandidates.delete(rule.id);
        continue;
      }

      const rebound = selectorTools.uniqueFingerprintMatch(document, rule.fingerprint);
      if (!rebound) {
        rebindCandidates.delete(rule.id);
        continue;
      }
      const selector = stableSelectorForRebind(rule, rebound);
      if (!selector) continue;
      runtime.protect(remember(rebound));
      sendRebind(rule, rebound, selector);
    }
  }

  function scheduleReconcile(delayMs = 50) {
    if (document.readyState === "loading") {
      if (waitsForDomReady) return;
      waitsForDomReady = true;
      document.addEventListener("DOMContentLoaded", () => {
        waitsForDomReady = false;
        scheduleReconcile();
      }, { once: true });
      return;
    }
    if (reconcileTimer !== null) return;
    reconcileTimer = setTimeout(reconcileRules, Math.max(0, delayMs));
  }

  function selectTargets(root) {
    if (root instanceof Element && rebindCandidates.size) {
      rebindCandidates.clear();
    }
    const targets = [];
    for (const rule of rules) {
      const rebindable = selectorTools.isRebindableFingerprint(rule.fingerprint);
      let localMatches;
      try {
        localMatches = runtime.selectWithin(root, rule.selector);
      } catch {
        continue;
      }
      if (!rebindable) {
        for (const element of localMatches) targets.push(remember(element));
        continue;
      }

      if (localMatches.length) {
        const globalMatches = matchingRuleElements(rule);
        if (globalMatches.length === 1) targets.push(remember(globalMatches[0]));
      }
    }
    if (rules.some((rule) => selectorTools.isRebindableFingerprint(rule.fingerprint))) {
      scheduleReconcile();
    }
    return [...new Set(targets)];
  }

  function updateRules(value) {
    if (reconcileTimer !== null) {
      clearTimeout(reconcileTimer);
      reconcileTimer = null;
    }
    restoreProtectedElements();
    rules = normalizedRules(value);
    rebindCandidates.clear();
    rebindNotifications.clear();
    rebindRetryCounts.clear();
    for (const element of selectTargets(document)) runtime.protect(element);
  }

  function updateSite(enabled, value) {
    mutationRisks?.setEnabled?.(Boolean(enabled));
    updateRules(enabled ? value : []);
  }

  async function reload() {
    const stored = await chrome.storage.local.get(storageKey);
    const site = stored[storageKey]?.sites?.[origin];
    updateSite(Boolean(site?.enabled), site?.rules);
  }

  const state = Object.freeze({ healthSnapshot, reload, updateRules, updateSite });
  Object.defineProperty(globalThis, stateSymbol, {
    configurable: false,
    enumerable: false,
    writable: false,
    value: state
  });

  runtime.registerAdapter({
    id: `site-rules:${origin}`,
    matches: (url) => url.origin === origin,
    protection: { select: selectTargets }
  });
  runtime.start();

  new MutationObserver((records) => {
    if (!rules.some((rule) => selectorTools.isRebindableFingerprint(rule.fingerprint))) return;
    if (records.some((record) => (
      record.type === "attributes" || record.removedNodes.length > 0
    ))) {
      scheduleReconcile();
    }
  }).observe(document, {
    attributes: true,
    attributeFilter: [
      "id", "class", "role", "type", "name",
      "data-testid", "data-test", "data-target", "data-component"
    ],
    childList: true,
    subtree: true
  });

  chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
    if (message?.type === "site-guard:rules-updated" && message.origin === origin) {
      updateSite(message.enabled !== false, message.rules);
      return false;
    }
    if (message?.type === "site-guard:get-rule-health" && message.origin === origin) {
      sendResponse(healthSnapshot());
      return false;
    }
    return false;
  });

  chrome.storage.onChanged?.addListener((changes, areaName) => {
    if (areaName === "local" && changes?.[storageKey]) void reload();
  });

  void reload();
})();
