import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = path.resolve(import.meta.dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));

const userscriptMetadata = `// ==UserScript==
// @name         Search Translate Guard for GitHub
// @namespace    local.github-search-translate-guard
// @version      ${manifest.version}
// @description  Keep GitHub search usable during automatic page translation, with a local fallback dialog when needed.
// @match        https://github.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==`;

const artifacts = [
  {
    output: "GitHub-Search-Translate-Guard.user.js",
    header: userscriptMetadata,
    sources: ["src/core.js", "src/adapters/github.js", "src/bootstrap.js"]
  },
  {
    output: "Site-Translate-Guard.content.js",
    header: "// Search Translate Guard: generated opt-in site protection content script.",
    sources: ["src/core.js", "src/adapters/site-rules.js"]
  }
];

function renderArtifact(artifact) {
  const sources = artifact.sources.map((relativePath) => {
    const source = fs.readFileSync(path.join(root, relativePath), "utf8");
    return `// Source: ${relativePath}\n${source.trim()}\n`;
  });
  return `${artifact.header}\n\n// Generated by node scripts/build.mjs. Do not edit directly.\n\n${sources.join("\n")}`;
}

let stale = false;
for (const artifact of artifacts) {
  const outputPath = path.join(root, artifact.output);
  const expected = renderArtifact(artifact);
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
    if (current !== expected) {
      console.error(`ERROR: ${artifact.output} is not up to date`);
      stale = true;
    } else {
      console.log(`${artifact.output} is up to date`);
    }
  } else {
    fs.writeFileSync(outputPath, expected, "utf8");
    console.log(`Generated ${artifact.output} from ${artifact.sources.length} source files`);
  }
}

if (stale) {
  console.error("Run: node scripts/build.mjs");
  process.exitCode = 1;
}
