import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = path.resolve(import.meta.dirname, "..");
const manifest = JSON.parse(fs.readFileSync(path.join(root, "manifest.json"), "utf8"));
const outputPath = path.join(root, "GitHub-Search-Translate-Guard.user.js");
const sourcePaths = [
  "src/core.js",
  "src/adapters/github.js",
  "src/bootstrap.js"
];

const metadata = `// ==UserScript==
// @name         Search Translate Guard for GitHub
// @namespace    local.github-search-translate-guard
// @version      ${manifest.version}
// @description  Keep GitHub search usable during automatic page translation, with a local fallback dialog when needed.
// @match        https://github.com/*
// @run-at       document-start
// @grant        none
// ==/UserScript==`;

const sources = sourcePaths.map((relativePath) => {
  const source = fs.readFileSync(path.join(root, relativePath), "utf8");
  return `// Source: ${relativePath}\n${source.trim()}\n`;
});
const expected = `${metadata}\n\n// Generated by node scripts/build.mjs. Do not edit directly.\n\n${sources.join("\n")}`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (current !== expected) {
    console.error("ERROR: GitHub-Search-Translate-Guard.user.js is not up to date");
    console.error("Run: node scripts/build.mjs");
    process.exitCode = 1;
  } else {
    console.log("Generated userscript is up to date");
  }
} else {
  fs.writeFileSync(outputPath, expected, "utf8");
  console.log(`Generated ${path.relative(root, outputPath)} from ${sourcePaths.length} source files`);
}
