import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const root = path.resolve(import.meta.dirname, "..");
const readJson = (relativePath) => JSON.parse(
  fs.readFileSync(path.join(root, relativePath), "utf8")
);
const fail = (message) => {
  console.error(`ERROR: ${message}`);
  process.exitCode = 1;
};

const manifest = readJson("manifest.json");
const packageJson = readJson("package.json");

if (manifest.manifest_version !== 3) fail("manifest_version must be 3");
if (!/^\d+(\.\d+){0,3}$/.test(manifest.version)) fail("invalid extension version");
if (!manifest.default_locale) fail("default_locale is required for localized metadata");
const allowedPermissions = new Set(["activeTab", "scripting", "storage"]);
for (const permission of manifest.permissions ?? []) {
  if (!allowedPermissions.has(permission)) fail(`unexpected browser API permission: ${permission}`);
}
for (const permission of allowedPermissions) {
  if (!manifest.permissions?.includes(permission)) fail(`missing browser API permission: ${permission}`);
}
if (manifest.host_permissions?.length) fail("unexpected host_permissions");
const optionalHosts = [...(manifest.optional_host_permissions ?? [])].sort();
if (JSON.stringify(optionalHosts) !== JSON.stringify(["http://*/*", "https://*/*"])) {
  fail("optional_host_permissions must contain only HTTP and HTTPS wildcard origins");
}
if (Number.parseInt(manifest.minimum_chrome_version, 10) < 96) {
  fail("minimum_chrome_version must support dynamic content scripts");
}
if (manifest.update_url) fail("store package must not define update_url");
if (manifest.key) fail("store package must not include a development key");
if (packageJson.version !== manifest.version) fail("package.json version must match manifest version");

const defaultMessages = readJson(`_locales/${manifest.default_locale}/messages.json`);
const resolveMessage = (value) => {
  const match = /^__MSG_(.+)__$/.exec(value);
  return match ? defaultMessages[match[1]]?.message : value;
};
const name = resolveMessage(manifest.name);
const description = resolveMessage(manifest.description);

if (!name || [...name].length > 75) fail("resolved name is missing or exceeds 75 characters");
if (!description || [...description].length > 132) fail("resolved description is missing or exceeds 132 characters");

const requiredFiles = new Set(["manifest.json"]);
for (const script of manifest.content_scripts ?? []) {
  for (const file of script.js ?? []) requiredFiles.add(file);
}
for (const file of Object.values(manifest.icons ?? {})) requiredFiles.add(file);
for (const file of [
  manifest.background?.service_worker,
  manifest.action?.default_popup,
  "Site-Translate-Guard.content.js",
  "src/risk-detector.js",
  "src/picker.js",
  "popup/popup.js",
  "popup/popup.css"
]) {
  if (file) requiredFiles.add(file);
}
for (const file of requiredFiles) {
  if (!fs.existsSync(path.join(root, file))) fail(`missing referenced file: ${file}`);
}

const requiredMessageKeys = [
  "extensionName", "extensionDescription", "fallbackTitle", "fallbackNotice",
  "fallbackInputLabel", "searchButton", "fallbackHint", "siteGuardActionTitle",
  "siteGuardTitle", "siteGuardBuiltInActive", "siteGuardEnable", "siteGuardSelect",
  "siteGuardClear", "siteGuardDisable", "siteGuardReloadHint", "siteGuardEnabled",
  "siteGuardDisabled", "siteGuardRuleCount", "siteGuardPermissionDenied",
  "siteGuardUnsupported", "siteGuardClearConfirm", "pickerInstruction",
  "pickerSelected", "pickerSuggested", "pickerProtect", "pickerParent",
  "pickerNextSuggestion", "pickerChooseManually", "pickerCancel", "pickerSaved",
  "pickerError"
];
for (const locale of ["en", "zh_CN"]) {
  const messages = readJson(`_locales/${locale}/messages.json`);
  for (const key of requiredMessageKeys) {
    if (!messages[key]?.message) fail(`missing ${key} in locale ${locale}`);
  }
}

const scriptPath = manifest.content_scripts?.[0]?.js?.[0];
if (scriptPath) {
  const source = fs.readFileSync(path.join(root, scriptPath), "utf8");
  if (!source.includes("Generated by node scripts/build.mjs")) {
    fail("content script must be generated by scripts/build.mjs");
  }
  if (!source.includes(`// @version      ${manifest.version}`)) {
    fail("userscript metadata version must match manifest version");
  }
}

const runtimeFiles = [
  scriptPath,
  "Site-Translate-Guard.content.js",
  manifest.background?.service_worker,
  "src/risk-detector.js",
  "src/picker.js",
  "popup/popup.js"
].filter(Boolean);
const forbidden = [
  /\beval\s*\(/,
  /new\s+Function\b/,
  /\bfetch\s*\(/,
  /XMLHttpRequest/,
  /import\s*\(/
];
for (const runtimeFile of runtimeFiles) {
  const source = fs.readFileSync(path.join(root, runtimeFile), "utf8");
  for (const pattern of forbidden) {
    if (pattern.test(source)) {
      fail(`forbidden remote/dynamic code pattern in ${runtimeFile}: ${pattern}`);
    }
  }
}

const siteContent = fs.readFileSync(path.join(root, "Site-Translate-Guard.content.js"), "utf8");
if (!siteContent.includes("Generated by node scripts/build.mjs")) {
  fail("opt-in site content script must be generated by scripts/build.mjs");
}

if (!process.exitCode) {
  console.log(`Validated ${name} v${manifest.version}`);
  console.log(`Default locale: ${manifest.default_locale}; site scope: ${manifest.content_scripts[0].matches.join(", ")}`);
}
